spring.application.name=produtos

spring.config.import=optional:file:.env[.properties]
spring.datasource.url=jdbc:postgresql://localhost:5432/${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

# Security Config
security.jwt.secret=${SECURITY_SECRET}
security.jwt.expiration-minutes=${SECURITY_EXPIRATION_MINUTES}
security.jwt.refresh-expiration-minutes=${SECURITY_REFRESH_EXPIRATION_MINUTES}